"""Build a synthetic run directory from the manifest.

The scoring engine is written before any VM exists, which means it needs input
before any VM exists too. This produces a run directory shaped exactly like one
a real guest would leave behind - two snapshots and a ``manifest.actual.json``
- with defects injected on purpose so the scorer has something to find.

It is emphatically **not** a substitute for a captured run, and every directory
it writes says so in its own metadata (``"synthetic": true``). A synthetic run
proves the scorer computes what we think it computes. Only a real one says
anything about the collector.

    python -m tests.tools.synthesize --os linux --out tests/recorded/synthetic-linux
"""

import argparse
import hashlib
import json
import os
from typing import Any, Dict, List, Optional

from ..manifest import Entry, Manifest, load

HOME = {"linux": "/home/tester", "mac": "/Users/tester", "win": "C:/Users/tester"}

#: Defects the default fixture carries. Chosen to exercise every outcome the
#: scorer can produce - a miss, a duplicate, an attributed invention and an
#: unattributed one - because a fixture that only contains successes tests
#: nothing but the happy path.
DEFAULT_DEFECTS = {
    "miss": ["M-SITE-08", "T-RT-04"],
    "duplicate": ["T-CHAN-04"],
    "invent_lookalike": ["N-07"],
    "invent_unattributed": True,
}


def build(manifest: Manifest, platform: str, defects: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Produce ``before``, ``after`` and ``manifest.actual`` for one OS."""
    defects = DEFAULT_DEFECTS if defects is None else defects
    home = HOME[platform]
    entries = manifest.for_platform(platform)
    records = [_record(entry, platform, home) for entry in entries]
    by_id = {record["id"]: record for record in records}
    for entry in entries:
        # A variant of a tool that never installed cannot be attempted either.
        if entry.variant_of and by_id.get(entry.variant_of, {}).get("status") != "installed":
            by_id[entry.id].update(status="unimplemented",
                                   reason="base %s did not install" % entry.variant_of)

    assets: List[Dict[str, Any]] = []
    for entry in entries:
        record = by_id[entry.id]
        if entry.id in defects.get("miss", []):
            continue
        if record["status"] != "installed" or entry.is_negative:
            continue
        assets.extend(_assets_for(entry, manifest, record, platform, home))
        if entry.id in defects.get("duplicate", []):
            assets.extend(_duplicate_of(entry, manifest, record, platform, home))

    for entry_id in defects.get("invent_lookalike", []):
        assets.append(_lookalike(manifest.by_id(entry_id), platform, home))
    if defects.get("invent_unattributed"):
        assets.append(_unattributed(home))

    assets = _dedupe(assets)
    after = _snapshot(platform, assets, manifest, home)
    before = _snapshot(platform, [], manifest, home, baseline=True)
    actual = {
        "run_id": "synthetic-%s" % platform,
        "os": platform,
        "home": home,
        "image": "synthetic",
        "collector": "0.1.0+synthetic",
        "synthetic": True,
        "note": "generated by tests/tools/synthesize.py - not a captured run",
        "applicable": len(entries),
        "installed": sum(1 for r in records if r["status"] == "installed"),
        "unavailable": sum(1 for r in records if r["status"] == "unavailable"),
        "failed": sum(1 for r in records if r["status"] == "failed"),
        "unimplemented": sum(1 for r in records if r["status"] == "unimplemented"),
        "entries": records,
    }
    return {"before": before, "after": after, "manifest.actual": actual,
            "canaries": _canaries(manifest)}


# -- what the runner would have recorded -------------------------------


def _record(entry: Entry, platform: str, home: str) -> Dict[str, Any]:
    """One row of ``manifest.actual.json``: reality, not intent."""
    record: Dict[str, Any] = {"id": entry.id, "catalog_id": entry.catalog_id,
                              "family": entry.family, "status": "installed"}
    if entry.install.get("requires") == "gpu":
        record.update(status="failed", reason="CUDA absent; service did not start")
        return record
    if entry.family in ("app-installer", "vendor-binary"):
        record.update(status="unimplemented", reason="source url unresolved in sources.yaml")
        return record
    if entry.family == "vscode-ext":
        record.update(status="unimplemented", reason="depends on T-APP-04, which is unimplemented")
        return record
    if entry.install.get("version"):
        record["version"] = entry.install["version"]
    path = _install_path(entry, platform, home)
    if path:
        record["path"] = path
    if entry.expect.get("install_method"):
        record["method"] = entry.expect["install_method"]
    return record


def _install_path(entry: Entry, platform: str, home: str) -> Optional[str]:
    if entry.shape in ("create", "declare"):
        return _expand(entry.path_for(platform), home)
    if entry.family == "npm-global":
        return "/usr/lib/node_modules/%s/bin/%s" % (entry.install["package"], _binary(entry))
    if entry.family == "pipx":
        return "%s/.local/pipx/venvs/%s/bin/%s" % (home, entry.install["package"], _binary(entry))
    if entry.family == "vendor-binary":
        return entry.install.get("dest")
    return None


def _binary(entry: Entry) -> str:
    return (entry.verify or entry.name).split(" ")[0]


def _expand(path: Optional[str], home: str) -> Optional[str]:
    if not path:
        return None
    return str(path).replace("~", home).replace("%USERPROFILE%", home).replace("%APPDATA%", home + "/AppData/Roaming")


# -- what a well-behaved collector would have reported ------------------


def _assets_for(entry: Entry, manifest: Manifest, record: Dict[str, Any],
                platform: str, home: str) -> List[Dict[str, Any]]:
    if entry.family == "channel-variant":
        # A second install of a tool already installed. A collector that is
        # working reports nothing new here, so the fixture emits nothing -
        # anything else would bake the defect into the baseline.
        return []
    if entry.shape == "declare":
        return [_mcp_asset(entry, record, platform, home)]
    if entry.shape == "create":
        return [_artifact_asset(entry, record, platform, home)]
    if entry.shape == "state":
        return _state_assets(entry, manifest, record, platform, home)
    if entry.family == "service" and entry.expect.get("kind") == "mcp_server":
        return [_undeclared_server(entry, record, home)]
    return [_install_asset(entry, record, platform, home)]


def _install_asset(entry: Entry, record: Dict[str, Any], platform: str, home: str) -> Dict[str, Any]:
    path = record.get("path") or ""
    return _asset(kind=entry.expect.get("kind", "cli_agent"), name=entry.name,
                  identity=entry.catalog_id or entry.id, catalog_id=entry.catalog_id,
                  version=record.get("version"), install_path=path,
                  install_root=os.path.dirname(path) if path else None,
                  install_method=entry.expect.get("install_method", "unknown"),
                  liveness=entry.expect.get("liveness", "installed"),
                  evidence=[("filesystem", path, "binary:%s" % _binary(entry))],
                  home=home)


def _mcp_asset(entry: Entry, record: Dict[str, Any], platform: str, home: str) -> Dict[str, Any]:
    declared = entry.declare
    args = ["[REDACTED]" if "{{canary:" in str(arg) else str(arg) for arg in declared.get("args", [])]
    risk: Dict[str, Any] = {"factors": [], "command": declared.get("command"), "args": args,
                            "pinned": entry.expect.get("pinned", True)}
    if declared.get("env"):
        risk["env_names"] = sorted(declared["env"])
    return _asset(kind="mcp_server", name=declared.get("server_name", entry.name),
                  identity="mcp:%s" % _hash(entry.id), version=None,
                  install_path=record.get("path"), install_method="unknown",
                  config_scope=entry.expect.get("config_scope", declared.get("scope")),
                  transport=entry.expect.get("transport", "stdio"), risk=risk,
                  network={"endpoint": declared.get("url")} if declared.get("url") else {},
                  evidence=[("config", record.get("path") or "", "config:%s" % declared.get("site"))],
                  home=home)


def _artifact_asset(entry: Entry, record: Dict[str, Any], platform: str, home: str) -> Dict[str, Any]:
    path = record.get("path") or ""
    risk: Dict[str, Any] = {"factors": []}
    if entry.create.get("command"):
        risk["command"] = str(entry.create["command"]).replace(
            "{{canary:%s}}" % (entry.canaries[0] if entry.canaries else ""), "[REDACTED]")
    if entry.create.get("variable"):
        risk["env_names"] = [entry.create["variable"]]
    return _asset(kind=entry.expect.get("kind", "skill"), name=os.path.basename(path.rstrip("/")) or entry.name,
                  identity=path, version=None, install_path=path,
                  install_root=os.path.dirname(path), install_method="agent_artifact",
                  config_scope=entry.expect.get("config_scope"), risk=risk,
                  evidence=[("filesystem", path, entry.subcategory)], home=home)


def _state_assets(entry: Entry, manifest: Manifest, record: Dict[str, Any],
                  platform: str, home: str) -> List[Dict[str, Any]]:
    """Runtime and identity states change a field on an asset another entry
    installed, so they contribute nothing of their own. Only a scheduler does."""
    if entry.state.get("parent"):
        parent = manifest.by_id(entry.state["parent"])
        base = manifest.by_id(parent.depends_on[0]) if parent.depends_on else None
        return [_asset(kind="agent", name=entry.state.get("launch", entry.name),
                       identity="child:%s" % _hash(entry.id), version=None,
                       install_method="agent_session", liveness="running",
                       parent_agent=base.catalog_id if base else None,
                       evidence=[("runtime", "", "process:child")], home=home)]
    if entry.state.get("method") != "scheduler":
        return []
    command = entry.state.get("command", "")
    return [_asset(kind="scheduled_agent", name=entry.state.get("task_name") or entry.name,
                   identity="sched:%s" % _hash(entry.id), version=None,
                   install_path=_expand(entry.state.get("path"), home),
                   install_method="agent_artifact", liveness="scheduled",
                   risk={"factors": [], "command": command.split(" ")[0], "args": command.split(" ")[1:]},
                   evidence=[("config", _expand(entry.state.get("path"), home) or entry.state.get("backend", ""),
                              "scheduler:%s" % entry.state.get("backend"))],
                   home=home)]


def _undeclared_server(entry: Entry, record: Dict[str, Any], home: str) -> Dict[str, Any]:
    """A server running that no config declares. The asset is not the point -
    the finding is."""
    return _asset(kind="mcp_server", name=entry.name, identity="mcp:%s" % _hash(entry.id),
                  version=None, install_method="unknown", liveness="running",
                  network={"port": entry.install.get("port")},
                  risk={"factors": ["undeclared"], "command": "node", "args": [], "pinned": False},
                  evidence=[("runtime", "", "listening:%s" % entry.install.get("port"))], home=home)


def _duplicate_of(entry: Entry, manifest: Manifest, record: Dict[str, Any],
                  platform: str, home: str) -> List[Dict[str, Any]]:
    """The usr-merge defect, made real: one binary, two spellings, two assets."""
    base = manifest.by_id(entry.variant_of) if entry.variant_of else entry
    twin = _install_asset(base, {"path": "/bin/%s" % _binary(base), "version": record.get("version")},
                          platform, home)
    twin["catalog_id"] = base.catalog_id
    twin["asset_id"] = _hash(entry.id + "twin")
    return [twin]


def _lookalike(entry: Entry, platform: str, home: str) -> Dict[str, Any]:
    """A negative control the collector fell for."""
    path = _expand(entry.path_for(platform) or (entry.detect.get("paths") or [""])[0], home)
    return _asset(kind="mcp_server", name=os.path.basename(path), identity="mcp:%s" % _hash(entry.id),
                  version=None, install_path=path, install_method="unknown",
                  risk={"factors": [], "command": path, "args": [], "pinned": False},
                  evidence=[("filesystem", path, "path-contains:mcp")], home=home)


def _unattributed(home: str) -> Dict[str, Any]:
    """An invention no control explains - the worse kind to receive."""
    path = "%s/.cache/ghost/ghost-agent" % home
    return _asset(kind="cli_agent", name="ghost-agent", identity="ghost-agent", version="9.9.9",
                  install_path=path, install_method="unknown",
                  evidence=[("filesystem", path, "binary:ghost-agent")], home=home)


def _asset(kind: str, name: str, identity: str, home: str, version: Optional[str] = None,
           install_path: Optional[str] = None, install_root: Optional[str] = None,
           install_method: str = "unknown", catalog_id: Optional[str] = None,
           config_scope: Optional[str] = None, transport: Optional[str] = None,
           liveness: str = "installed", risk: Optional[Dict[str, Any]] = None,
           network: Optional[Dict[str, Any]] = None, parent_agent: Optional[str] = None,
           evidence: Optional[List[Any]] = None) -> Dict[str, Any]:
    return {
        "kind": kind, "name": name, "identity": identity, "owner": "tester",
        "vendor": None, "version": version, "install_path": install_path,
        "install_root": install_root or (os.path.dirname(install_path) if install_path else None),
        "install_method": install_method, "catalog_id": catalog_id,
        "evidence": [{"probe": "synthetic", "channel": channel, "path": path or "",
                      "matched_on": matched, "confidence": 0.6}
                     for channel, path, matched in (evidence or [])],
        "signature": {}, "network": network or {}, "config_scope": config_scope,
        "liveness": liveness, "location": None, "transport": transport, "parent_agent": parent_agent,
        "models": [], "flags": [], "risk": risk or {"factors": []}, "last_used": None,
        "asset_id": _hash(identity + (install_path or "")),
    }


def _dedupe(assets: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Two entries can legitimately describe one asset - a running tool is the
    tool - and a snapshot with a repeated asset_id is one the collector's own
    diff refuses to read."""
    seen: Dict[str, Dict[str, Any]] = {}
    for asset in assets:
        existing = seen.get(asset["asset_id"])
        if existing is None:
            seen[asset["asset_id"]] = asset
        else:
            existing["evidence"].extend(asset["evidence"])
    return list(seen.values())


def _snapshot(platform: str, assets: List[Dict[str, Any]], manifest: Manifest,
              home: str, baseline: bool = False) -> Dict[str, Any]:
    review: List[Dict[str, Any]] = []
    errors: List[Dict[str, str]] = []
    findings: List[Dict[str, Any]] = []
    if not baseline:
        for asset in assets:
            if "undeclared" in (asset.get("risk") or {}).get("factors", []):
                findings.append({"finding": "undeclared_mcp_server", "asset_id": asset["asset_id"],
                                 "name": asset["name"], "severity": "high"})
        for entry in manifest.for_platform(platform):
            if entry.must_be_reviewed:
                path = _expand(entry.path_for(platform), home)
                review.append({"name": os.path.basename(path or entry.name), "path": path,
                               "kind": "cli_agent", "state": "probable_ai_unclassified",
                               "signals": ["name_hints_ai", "invokes_model_api"], "score": 0.7,
                               "sessions": 0, "priority": 0.7, "threshold": 0.6})
            if entry.explains_error:
                errors.append({"probe": "cli_agent", "path": _expand(entry.path_for(platform), home) or "",
                               "message": "broken symlink"})
    return {
        "hostname": "adr-disco-%s" % platform, "username": "tester", "platform": platform,
        "timestamp": "2026-08-22T09:%02d:00Z" % (0 if baseline else 41),
        "assets": assets, "review_queue": review, "findings": findings, "errors": errors,
        "stats": {"asset_count": len(assets), "review_queue_count": len(review),
                  "error_count": len(errors), "wall_ms": 3120.0 if baseline else 6480.0,
                  "catalog_version": "2026.08.18", "probes": {}, "coverage": {}},
    }


def _canaries(manifest: Manifest) -> Dict[str, str]:
    """Values a run would have generated. Deterministic here so the fixture is
    reproducible; a real run generates them fresh and never commits them."""
    return {item["name"]: item["shape"].format(random="0" * 32) if "{random" in item["shape"]
            else item["shape"] for item in manifest.canaries}


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--os", dest="platform", default="linux", choices=("mac", "linux", "win"))
    parser.add_argument("--out", required=True, help="run directory to write")
    parser.add_argument("--clean", action="store_true", help="inject no defects")
    args = parser.parse_args(argv)

    manifest = load()
    built = build(manifest, args.platform, defects={} if args.clean else None)
    os.makedirs(args.out, exist_ok=True)
    for name, payload in built.items():
        with open(os.path.join(args.out, name + ".json"), "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
    print("wrote %s: %d assets" % (args.out, len(built["after"]["assets"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
